In [1]:
import numpy as np
import pandas as pd

from surprise import NormalPredictor
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate
from surprise.model_selection import train_test_split
from surprise import SVD, KNNWithZScore, KNNBasic
from surprise import Dataset
from surprise import accuracy
from surprise import dump
import matplotlib.pyplot as plt
import matplotlib

In [2]:
final_data = pd.read_csv("librarydata/rename.csv", encoding='utf-8',index_col=0)

In [3]:
book_count = pd.read_csv("librarydata/book_count.csv",encoding='utf-8',index_col=0)

In [4]:
user_item = pd.read_csv("librarydata/user_item_rename.csv", encoding='utf-8', index_col=0)

In [32]:
book_count.head(5)

                                            bookname  count
0   PowerPoint 97 中文版傻瓜书A Powerpoint 97 Zhong Wen...      1
1                  Pro/ENGINEER Wildfire (中文版) 工程图设计      1
2                                                伦理学      1
3                                              寂静的春天      1
4                                               战争指导      1

In [16]:
user_item["bookname"].head(5)

0                                              [30599]
1                                 [12100, 5148, 12100]
2                         [38893, 38890, 38891, 38892]
3             [14433, 9888, 41098, 9889, 41101, 14444]
4    [53000, 53000, 49304, 51402, 19777, 41129, 461...
Name: bookname, dtype: object

In [8]:
user_item["bookname"]=user_item["bookname"].apply(lambda x: eval(x))

In [9]:
final_data["count"] = False

In [10]:
for i in final_data.index:
    if len(user_item["bookname"][int(final_data["name"][i])]) <=10 and book_count["count"][int(final_data["bookname"][i])] <= 10:
        final_data.iloc[i,8] = True
    else:
        continue

In [11]:
final_data[(final_data["count"]==True)]

,name,bookname,category,day,minute,rank,time,timestamp,count
0,12495,13720,7-5051-0077-7,2010-01-04,13:50:27,1,2010-01-04 13:50:27,1.262584e+09,True
5,15176,48565,7-01-000172-3,2010-01-12,09:17:39,2,2010-01-12 09:17:39,1.263259e+09,True
13,15971,22666,7-80034-321-9,2010-01-11,12:24:29,2,2010-01-11 12:24:29,1.263184e+09,True
14,9168,22666,7-80034-321-9,2010-01-07,10:42:26,2,2010-01-07 10:42:26,1.262832e+09,True
15,1566,41272,7-80513-138-4,2010-01-12,15:24:32,2,2010-01-12 15:24:32,1.263281e+09,True
19,1572,41272,7-80513-138-4,2010-01-10,15:01:10,2,2010-01-10 15:01:10,1.263107e+09,True
26,15962,20167,15034.3159,2010-01-11,12:30:33,5,2010-01-11 12:30:33,1.263184e+09,True
27,241,20167,15034.3159,2010-01-11,14:58:13,5,2010-01-11 14:58:13,1.263193e+09,True
29,8732,28487,7-111-03181-4,2010-01-13,14:05:09,1,2010-01-13 14:05:09,1.263363e+09,True
30,13174,42914,7-111-01245-3,2010-01-11,11:39:31,2,2010-01-11 11:39:31,1.263181e+09,True
35,8732,32981,15031.204,2010-01-13,14:05:05,1,2010-01-13 14:05:05,1.263363e+09,True
37,15543,32825,7-111-04438-X,2010-01-04,15:45:33,1,2010-01-04 15:45:33,1.262591e+09,True
46,15929,25829,7-111-00792-1,2010-01-11,19:04:02,1,2010-01-11 19:04:02,1.263208e+09,True
52,13825,32926,7-118-01630-6,2010-01-11,18:17:28,2,2010-01-11 18:17:28,1.263205e+09,True
53,13823,32926,7-118-01630-6,2010-01-11,18:17:06,2,2010-01-11 18:17:06,1.263205e+09,True
62,15405,24245,15216.204,2010-01-14,14:58:54,5,2010-01-14 14:58:54,1.263452e+09,True
63,15405,24245,15216.204,2010-01-14,14:58:30,5,2010-01-14 14:58:30,1.263452e+09,True
69,13829,50336,7-111-02820-1,2010-01-05,09:28:55,1,2010-01-05 09:28:55,1.262655e+09,True
73,15405,50255,7-118-00797-8,2010-01-14,14:58:59,1,2010-01-14 14:58:59,1.263452e+09,True
80,8831,24060,7-5624-1822-5,2010-01-03,16:43:32,5,2010-01-03 16:43:32,1.262508e+09,True
81,8831,24060,7-5624-1822-5,2010-01-03,16:43:27,5,2010-01-03 16:43:27,1.262508e+09,True
82,15940,50325,7-111-05680-9,2010-01-12,12:06:54,1,2010-01-12 12:06:54,1.263269e+09,True
86,573,32726,7-111-03278-0,2010-01-04,18:06:22,1,2010-01-04 18:06:22,1.262600e+09,True
87,15076,32726,7-111-03278-0,2010-01-14,16:32:57,1,2010-01-14 16:32:57,1.263458e+09,True
92,16176,52697,7-307-02466-7,2010-01-10,12:00:18,1,2010-01-10 12:00:18,1.263096e+09,True
99,13164,28485,7-111-09372-0,2010-01-13,18:17:10,2,2010-01-13 18:17:10,1.263378e+09,True
100,1132,24013,7-03-009095-0,2010-01-12,14:11:46,1,2010-01-12 14:11:46,1.263277e+09,True
101,16180,52746,7-313-02560-2,2010-01-10,16:11:31,1,2010-01-10 16:11:31,1.263111e+09,True
103,4833,48953,7-5051-0604-x,2010-01-13,12:40:39,1,2010-01-13 12:40:39,1.263358e+09,True
108,3175,27401,7-80675-006-1,2010-01-12,15:25:19,2,2010-01-12 15:25:19,1.263281e+09,True
...,...,...,...,...,...,...,...,...,...
178143,761,30097,978-7-311-03051-3,2010-07-17,10:50:34,5,2010-07-17 10:50:34,1.279335e+09,True
178144,761,44177,978-7-81118-374-0,2010-07-17,10:50:43,1,2010-07-17 10:50:43,1.279335e+09,True
178145,761,44356,978-7-301-14558-6,2010-07-17,10:50:48,1,2010-07-17 10:50:48,1.279335e+09,True
178146,761,14594,978-7-305-06175-2,2010-07-17,10:50:53,1,2010-07-17 10:50:53,1.279335e+09,True
178147,761,30097,978-7-311-03051-3,2010-07-17,10:50:57,5,2010-07-17 10:50:57,1.279335e+09,True
178148,761,19419,7-5063-3477-1,2010-07-17,10:51:04,2,2010-07-17 10:51:04,1.279335e+09,True
178154,330,51611,978-7-5100-0519-0,2010-07-17,10:58:17,1,2010-07-17 10:58:17,1.279335e+09,True
178214,144,13786,7-81045-821-3,2010-07-17,14:08:33,1,2010-07-17 14:08:33,1.279347e+09,True
178230,3292,47103,7-03-018117-4,2010-07-17,14:22:18,2,2010-07-17 14:22:18,1.279348e+09,True
178263,793,4227,7-111-20586-3,2010-07-17,14:47:21,2,2010-07-17 14:47:21,1.279349e+09,True
178264,793,4127,978-7-302-19428-6,2010-07-17,14:47:29,1,2010-07-17 14:47:29,1.279349e+09,True
178265,1369,30155,7-302-14274-2,2010-07-17,14:50:51,3,2010-07-17 14:50:51,1.279349e+09,True
178276,111,28001,978-7-02-006013-9,2010-07-18,10:05:28,3,2010-07-18 10:05:28,1.279419e+09,True
178277,111,23001,978-7-5004-5513-4,2010-07-18,10:05:36,3,2010-07-18 10:05:36,1.279419e+09,True
178278,111,30635,7-80653-660-4,2010-07-18,10:05:43,1,2010-07-18 10:05:43,1.279419e+09,True
178281,8178,37439,978-7-5063-4769-3,2010-07-18,10:23:43,2,2010-07-18 10:23:43,1.279420e+09,True
178282,8178,8550,978-7-5387-2291-8,2010-07-18,10:23:48,1,2010-07-18 10:23:48,1.279420e+09,True
178322,320,2364,978-7-302-15582-9,2010-07-18,10:51:31,1,2010-07-18 10:51:31,1.279421e+09,True
178323,320,2886,7-307-04823-X,2010-07-18,10:51:35,2,2010-07-18 10:51:35,1.279421e+09,True
178326,222,18675,978-7-308-06310-4,2010-07-18,10:53:26,2,2010-07-18 10:53:26,1.279422e+09,True
178327,222,18714,7-80011-987-4,2010-07-18,10:53:30,1,2010-07-18 10:53:30,1.279422e+09,True
178328,222,18808,978-7-302-19782-9,2010-07-18,10:53:32,1,2010-07-18 10:53:32,1.279422e+09,True
178373,4860,25809,7-80186-529-4,2010-07-18,12:42:25,3,2010-07-18 12:42:25,1.279428e+09,True
178374,4860,47953,7-5371-3480-4,2010-07-18,12:42:31,2,2010-07-18 12:42:31,1.279428e+09,True
178428,16083,46457,978-7-229-00787-4,2010-07-18,08:43:34,1,2010-07-18 08:43:34,1.279414e+09,True
178458,759,3662,978-7-121-06456-2,2010-07-18,09:29:09,1,2010-07-18 09:29:09,1.279417e+09,True
178459,759,1190,978-7-81124-209-6,2010-07-18,09:29:15,2,2010-07-18 09:29:15,1.279417e+09,True
178460,759,12470,978-7-80248-322-4,2010-07-18,09:29:20,1,2010-07-18 09:29:20,1.279417e+09,True
178461,759,16232,978-7-5027-6951-2,2010-07-18,09:29:26,3,2010-07-18 09:29:26,1.279417e+09,True
178462,759,5180,978-7-04-025129-6,2010-07-18,09:29:31,3,2010-07-18 09:29:31,1.279417e+09,True

In [23]:
user_item.head(5)

                                            bookname
0                                            [30599]
1                               [12100, 5148, 12100]
2                       [38893, 38890, 38891, 38892]
3           [14433, 9888, 41098, 9889, 41101, 14444]
4  [53000, 53000, 49304, 51402, 19777, 41129, 461...

In [12]:
final_data = final_data[(final_data["count"]==False)]

In [5]:
final_data = final_data[["name","bookname","rank"]]

In [14]:
final_data.to_csv("librarydata/follow_surprise.csv",encoding='utf-8')

In [3]:
final_data = pd.read_csv("librarydata/follow_surprise.csv",encoding='utf-8')

In [6]:
final_data = final_data.reindex(np.random.permutation(final_data.index))

In [7]:
final_data.head(5)

         name  bookname  rank
173609   3008     50457     5
15038    4898     42939     5
46621    6464     20056     5
33696   11591     29178     2
144794   6905       649     1

In [8]:
# Creation of the dataframe. Column names are irrelevant.
df = pd.DataFrame(final_data)

# A reader is still needed but only the rating_scale param is requiered.
reader = Reader(rating_scale=(1, 5))

# The columns must correspond to user id, item id and ratings (in that order).
data = Dataset.load_from_df(df, reader)

# We can now use this dataset as we please, e.g. calling cross_validate
# cross_validate(NormalPredictor(), data, cv=2)

In [9]:
trainset, testset = train_test_split(data, test_size=.01)

In [10]:
trainset.all_items()

range(0, 53077)

In [15]:

algo = SVD(n_factors=100, n_epochs=200)

# Train the algorithm on the trainset, and predict ratings for the testset
algo.fit(trainset)
predictions = algo.test(testset)

# Then compute RMSE
accuracy.rmse(predictions)

RMSE: 0.6044

0.6043888317228193

In [14]:
algo_knn = KNNBasic(sim_options={'user_based':True})

# Train the algorithm on the trainset, and predict ratings for the testset
#algo_knn.fit(trainset)
predictions_knn = algo_knn.test(testset)

# Then compute RMSE
accuracy.rmse(predictions_knn)

RMSE: 1.0274

1.0274083796699733

In [ ]:
for i in final_data.index:
    uid=final_data["name"][i]
    iid=final_data["bookname"][i]
    pred = algo.predict(uid, iid, r_ui=final_data["rank"][i], verbose=True)

In [29]:
i = 100088
uid=final_data["name"][i]
iid=final_data["bookname"][i]
pred = algo.predict(uid, iid, verbose=True)
# type(pred.est)

user: 7352       item: 48758      r_ui = None   est = 2.31   {'was_impossible': False}

In [24]:
algo

In [16]:
dump.dump("librarydata/model.md", algo=algo, predictions=predictions)

In [11]:
dump.dump("librarydata/model_knn.md", algo=algo_knn, predictions=predictions_knn)

In [7]:
predictions, algo = dump.load("../librarydata/model.md")

In [19]:
for i in algo.compute_baselines():
    print(len(i))

12414
44884

In [36]:
for i in algo.get_neighbors(12000,5):
    print(book_count["bookname"][i])

2009年全国一、二级注册建筑师考试模拟题解.1,知识.第4版
AutoCAD建筑三维建模技术
Cisco网络技术教程
Cisco路由器防火墙安全
D-妖杀行

In [22]:
a = algo.compute_similarities()

Computing the msd similarity matrix...
Done computing similarity matrix.

In [34]:
import matplotlib.pyplot as plt

In [17]:
accuracy.rmse(predictions)

RMSE: 0.6044

0.6043888317228193

In [24]:
algo_knn = KNNBasic()

# Train the algorithm on the trainset, and predict ratings for the testset
algo_knn.fit(trainset)
predictions_knn = algo.test(testset)

# Then compute RMSE
accuracy.rmse(predictions_knn)

Computing the msd similarity matrix...
Done computing similarity matrix.
RMSE: 1.0904

1.0903983480812682

In [87]:
trainset.all_items()

range(0, 45481)

In [18]:
# Fixing random state for reproducibility
x = range(0,len(predictions_knn))
y_ui = [x.r_ui for x in predictions_knn]
y_est = [x.est for x in predictions_knn]
plt.figure(0,figsize=(60,5))
plt.scatter(x, y_ui, c='red')
plt.scatter(x, y_est, c='blue')
plt.xlabel("index")
plt.ylabel("score")
# plt.legend(loc=2)
plt.show()
plt.close(0)
x = range(0,len(predictions))[:]
y_ui = [x.r_ui for x in predictions][:]
y_est = [x.est for x in predictions][:]
plt.figure(1,figsize=(60,5))
plt.scatter(x, y_ui, c='red')
plt.scatter(x, y_est, c='blue')
plt.xlabel("index")
plt.ylabel("score")
# plt.legend(loc=2)
plt.show()

NameError: name 'predictions_knn' is not defined

In [37]:
baselines = algo_knn.compute_similarities()

Computing the msd similarity matrix...
Done computing similarity matrix.